### ISSUE TITLE
unable to compile due to circular dependencies

### ISSUE THREAD

**Issue by blshkv** [libimobiledevice/usbmuxd#10]
the latest HEAD fails to compile with the following error:

```
checking for libimobiledevice... no
configure: error: preflight worker support requested but libimobiledevice could not befound
```

In turn, I'm unable to compile libimobiledevice-1.1.6:

```
checking for libusbmuxd... no
configure: error: Package requirements (libusbmuxd >= 1.0.9) were not met:
Requested 'libusbmuxd >= 1.0.9' but version of libusbmuxd is 1.0.8
```

**Comment by marksolaris** [comment]
The full install... you need to set your PKG_CONFIG_PATH variable to <prefix>/lib/pkgconfig so that each new package you compile can find the latest dependencies.

libplist
libusbmuxd
libimobiledevice
usbmuxd
ifuse
libzip
ideviceinstaller
libirecovery
idevicerestore
libideviceactivation
