### ISSUE TITLE
Can we finally update the version numbers?

### ISSUE THREAD

**Issue by Overc1ocker** [libimobiledevice/usbmuxd#105]
First of all, I’d like to thank all the devs for all the time they put in trying to make devices from the fruity company work on Linux. There is one small issue however, the last major update was 2 years ago. Isn’t it time to release a new version? Instead of just cloning github? It would be helpful to distro maintainers, and even the average user. Why not start fresh with libimobiledevice 3.0?

**Comment by FunkyM** [comment]
Closing as version [1.1.1](/libimobiledevice/usbmuxd/releases/tag/1.1.1) has been released.
