### ISSUE TITLE
your ssl cert has expired

### ISSUE THREAD

**Issue by Lision** [libimobiledevice/usbmuxd#113]
$ brew install --HEAD usbmuxd
==> Cloning https://git.sukimashita.com/libusbmuxd.git
Updating /Users/lision/Library/Caches/Homebrew/usbmuxd--git
fatal: unable to access 'https://git.sukimashita.com/libusbmuxd.git/': SSL certificate problem: certificate has expired
Error: An exception occurred within a child process:
DownloadError: Failed to download resource "usbmuxd"
Failure while executing; git fetch origin exited with 128. Here's the output:
fatal: unable to access 'https://git.sukimashita.com/libusbmuxd.git/': SSL certificate problem: certificate has expired

**Comment by mexmer** [comment]
you need to post this to sukimashita repository owner, this is github.
