### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Keruspe** [libimobiledevice/usbmuxd#115]
It has been ages since last release, is any new release planned?

**Comment by kloczek** [comment]
Yes .. please :)

**Comment by kloczek** [comment]
Is it any chance to make new release soon?

**Comment by FunkyM** [comment]
Closing as version [1.1.1](/libimobiledevice/usbmuxd/releases/tag/1.1.1) has been released.

**Comment by kloczek** [comment]
Thx.
Just made full update with libplist-2.0 and looks like everything builds correctl;y :)
