### ISSUE TITLE
`brew rm usbmuxd` does not actually remove usbmuxd

### ISSUE THREAD

**Issue by lochlainn** [libimobiledevice/usbmuxd#123]
After running brew rm, I am still seeing the agent in launchctl:

```
sh-3.2# launchctl list | grep usbmuxd
48958   -9      com.apple.usbmuxd
```

**Comment by nikias** [comment]
You do realize that Apple ships its own usbmuxd? You wouldn't want to actually install your own copy on macOS...

**Comment by nikias** [comment]
Also this isn't a bug in usbmuxd. Closing.
