### ISSUE TITLE
Is it possible to customize network interface name ?

### ISSUE THREAD

**Issue by sancelot** [libimobiledevice/usbmuxd#125]
is it possible to customize the ipheth interface name (eg iphone instead of eth1)  ?

**Comment by mexmer** [comment]
this not issue of library or usbmuxd, it's thing of linux kernel driver. depending on network stack you use, some allow interface aliasing. but that solely depends on your system.

**Comment by nikias** [comment]
Perfect answer from @mexmer. Closing since this is not a bug.
