### ISSUE TITLE
incorrect udev rules added for "Support T2 chip in restore mode"

### ISSUE THREAD

**Issue by dogben** [libimobiledevice/usbmuxd#132]
In https://github.com/libimobiledevice/usbmuxd/commit/ec5ff91cfabd30637f8af8f5c79baf4d7818ce57, udev/39-usbmuxd.rules.in was modified to use a regex in a udev label. Based on docs, the label values can be a shell glob, but not a regexp. See 'man udev': "Most of the fields support a shell style pattern matching." https://linux.die.net/man/7/udev

I think `5ac/12[9a][0-9a-f]/*|5ac/8600/*` would work, but haven't tested it.

See discussion here: https://github.com/libimobiledevice/usbmuxd/commit/ec5ff91cfabd30637f8af8f5c79baf4d7818ce57#commitcomment-36656411

**Comment by nikias** [comment]
Fixed with commit 8a69f1a78a58476f77b66916091d2405d0cd815f.
