### ISSUE TITLE
Cannot run autogen.sh on Ubuntu 19.0

### ISSUE THREAD

**Issue by oliviergf** [libimobiledevice/usbmuxd#133]
when running autogen.sh i get
[...]
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
./configure: line 11544: syntax error near unexpected token `libusb,'
./configure: line 11544: `PKG_CHECK_MODULES(libusb, libusb-1.0 >= 1.0.9)'

and then it stops.

**Comment by nikias** [comment]
Install pkgconfig.

**Comment by oliviergf** [comment]
thanks it worked
