### ISSUE TITLE
configure: error: libpthread is required to build usbmuxd

### ISSUE THREAD

**Issue by XanaduAPI** [libimobiledevice/usbmuxd#155]
In the process of compiling Android version, I encountered the following error. How can I solve it?

Compilation parameters:./autogen.sh --host=arm-linux-androideabi --prefix=$ANDROID_ARM_32

ANDROID_ARM_32=$ANDROID_ARM_32/ARM_32
$NDK_HOME/build/tools/make-standalone-toolchain.sh --platform=android-24 --arch=arm --install-dir=$ANDROID_ARM_32/ARM_32

**Comment by XanaduAPI** [comment]
![image](https://user-images.githubusercontent.com/45027459/100560368-8c297880-32f0-11eb-8451-77a575223882.png)

**Comment by nikias** [comment]
I think on Android, you don't need to pass -lpthread so you can disable this check in configure.ac:
https://github.com/libimobiledevice/usbmuxd/blob/63d1164e736d7419198d1b737d10a9aae85bef98/configure.ac#L22

**Comment by XanaduAPI** [comment]
@nikias Thank you very much. I just compiled it successfully.

**Comment by XanaduAPI** [comment]
@nikias  
![image](https://user-images.githubusercontent.com/45027459/100561026-9b112a80-32f2-11eb-8f0e-9ea5e9a22f2f.png)

The above error occurred later.

I'm blocking the

//#define malloc rpl_ malloc

//#define realloc rpl_ realloc

And it worked
