### ISSUE TITLE
About building and running on Android

### ISSUE THREAD

**Issue by xanadu-lee** [libimobiledevice/usbmuxd#179]
I see the description of your home page.

Cross-Platform: Tested on Linux, macOS, Windows and Android platforms

I'm curious that when I use java code to simulate, I can't open the multiplexing interface of iPhone.

According to
https://github.com/libimobiledevice/usbmuxd/blob/e3a3180b9b380ce9092ee0d7b8e9d82d66b1c261/src/usb.c#L477
I found the interfaces numbered 6 and 8.

When I tried to open it with android.hardware.usb.UsbDeviceConnection.claimInterface, I got an error.

So, I would like to ask you, have you successfully run it on Android and connected to the device?

If you have successfully connected to the device, can you say what changes you have made? Whether internal or external, what should I pay attention to?

I can only run it on arm at present, because the permissions on Java do not allow me to open the specified interface.

**Comment by KokoseiJ** [comment]
Well, then it might be better to just carry other embeddable devices. maybe raspberry pi or rooted donor phone.
Android itself is very much limited without acquiring root permission. You can't just think of it as a usual linux environment.

**Comment by xanadu-lee** [comment]
Some companies can connect directly on Android. I don't know how they do it.

**Comment by mexmer** [comment]
@xanadu-lee if you mean that some vendors have app that can do direct import from iphone ... then those are vendor apps, they have root access and they can run usbmuxd and access iphone trough libimobile (yes, that's what they use, libimobile), prime example is when you setup new google nexus, it has option to import data from iphone, and samsung galaxy likewise ... but it's only available in app that is from phone manufacturer, because they can run own apps, on own device as root.

**Comment by xanadu-lee** [comment]
@mexmer 
I mean, some people can run usbmuxd and connect to iPhone directly on Android of ordinary users.
It's like using android as a PC.
Trust and communication are OK.

**Comment by mexmer** [comment]
@xanadu-lee if you root your phone, and install and launch usbmuxd, any application can communicate with iphone trough libimobile ... application itself doesn't need to run under root, only installation of usbmuxd requires it.

**Comment by xanadu-lee** [comment]
@mexmer 
I think maybe I didn't describe it clearly.
On any Android phone, such as Google, Xiaomi, etc.
After installation, you can communicate.
No pre installation is required.
I just don't know how they did it.

**Comment by mexmer** [comment]
what software you talking about?

**Comment by xanadu-lee** [comment]
@mexmer 
http://imzs.net/
https://www.google.com/search?q=%E6%9E%9C%E7%B1%B3%E5%8A%A9%E6%89%8B

**Comment by nikias** [comment]
I am not an Android guy but the only thing really required for usbmuxd to work is access to USB devices via libusb. Not sure how that works permission wise. The listening socket can be a tcp socket of any choice (see command line argument --socket, obviously all libimobiledevice (more precise: libusbmuxd) consumers need to point to the new socket, there's an env var LIBUSBMUXD_SOCKET_ADDRESS for that) and the path for the pairing records can be changed in usbmuxd's source code accordingly, which defaults to /var/lib/usbmuxd which probably doesn't exist on Android.

**Comment by xanadu-lee** [comment]
I saw this
https://gitee.com/vonchenchen/usbmuxd_android

It seems that usbmuxd is implemented in Java.
It depends on using yourself as a part of the iPhone, not the iPhone as a part of Android.

**Comment by mexmer** [comment]
@xanadu-lee link you have sent is not loading (imzs one), so no idea about that program, other guy repository with usbmuxd written in java ... it might work (had not tested it), but it strictly depends on what interface is allowed by device manufacturer. eg. if it will detect iphone on USB (probly it will at least as MTP storage) and also if it will access to mux interface profile .... it will work ... but it also might not work ... general android support for usb devices is limited to standard generic profiles like mass storage, MTP storage, camera, HID (keyboard, mouse).

**Comment by xanadu-lee** [comment]
@mexmer 
I found that it should be handled using UsbAccessory.
Specific not verified :  [usbmuxd_android >> USBConnStatusManager](https://gitee.com/vonchenchen/usbmuxd_android/blob/master/app/src/main/java/com/vonchenchen/usbmuxd_android/usbmuxd/usb/USBConnStatusManager.java)

**Comment by cczhr** [comment]
> @mexmer I found that it should be handled using UsbAccessory. Specific not verified : [usbmuxd_android >> USBConnStatusManager](https://gitee.com/vonchenchen/usbmuxd_android/blob/master/app/src/main/java/com/vonchenchen/usbmuxd_android/usbmuxd/usb/USBConnStatusManager.java)

稍微研究下那个app“果米助手” 里面有一个 liblinux.so 看了一下里面的方法应该就是用来连接iphone的  反编译看了下直接传了个context进去 
 
![image](https://user-images.githubusercontent.com/20502238/155497108-d8a1752c-0c8c-499e-b26e-0e47318b4cdb.png)

![image](https://user-images.githubusercontent.com/20502238/155497206-90db7159-df25-44bb-b522-30e974039294.png)

[liblinux.zip](https://github.com/libimobiledevice/usbmuxd/files/8131168/liblinux.zip)
