### ISSUE TITLE
39-usbmuxd.rules udev breaks touchbar on Ubuntu 21.10 and 22.04

### ISSUE THREAD

**Issue by davidjo** [libimobiledevice/usbmuxd#187]
Reporting this known issue in the hope this will be found from google searches.

**Comment by nikias** [comment]
What touchbar, and do you have any more detailed debug/log information or messages?

**Comment by davidjo** [comment]
see issue #138

**Comment by nikias** [comment]
Why open another ticket for that? Just comment on the existing one.
