### ISSUE TITLE
Timeouts should not be calculated using gettimeofday()

### ISSUE THREAD

**Issue by WcRnm** [libimobiledevice/usbmuxd#22]
Timeouts in usbmuxd are calculated using gettimeofday(). This can cause invalid timeout durations to be calculated if the time is changed.

Our fix was to use this function instead of gettimeofday():

```
 void gettickcount(struct timeval * tv)
 {
    struct timespec ts;
    if(0 == clock_gettime(CLOCK_MONOTONIC, &ts)) {
        tv->tv_sec = ts.tv_sec;
        tv->tv_usec = ts.tv_nsec / 1000;
    }
    else {
        gettimeofday(tv, NULL);
    }
}
```

**Comment by nikias** [comment]
This has been fixed with commit 04e07442bbc8a5d8515fa1eea52cb15ebd2cc992.
