### ISSUE TITLE
New version?🤔

### ISSUE THREAD

**Issue by kloczek** [libimobiledevice/usbmuxd#223]
Looking on https://github.com/libimobiledevice/usbmuxd/compare/1.1.1...master and fact that last release was +3 years ago I think that it would be good to flush all those commits and release new version.

Do you have any plans to do that soon? 🤔 (just asking)

**Comment by WhyNotHugo** [comment]
Duplicate of https://github.com/libimobiledevice/usbmuxd/issues/168

**Comment by kloczek** [comment]
OK closing.
BTW .. any update? 🤔
