### ISSUE TITLE
usbmuxd should restart after Device unplugged

### ISSUE THREAD

**Issue by xswqaz** [libimobiledevice/usbmuxd#87]
After device unplugged, New device is failed to connect with error

`
[09:50:35.915][3] Could not get old configuration descriptor for device 3-12: -5
[09:50:35.924][2] Could not get serial number for device 3-12: -6
`

It success to connect new device after pkill usbmuxd and restart usbmuxd

**Comment by nikias** [comment]
This is definitely not the right approach. Actually this should be fixed with this commit: https://github.com/libimobiledevice/usbmuxd/commit/d29b74db77433a80fa2eb293216e8f572ffe4c57
